apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rnn-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-rnn-model
  template:
    metadata:
      labels:
        app: my-rnn-model
    spec:
      containers:
      - name: my-rnn-model-container
        image: my_rnn_model:latest  # Correct name with underscores
        ports:
        - containerPort: 5000
