apiVersion: v1
kind: Service
metadata:
  name: my-rnn-model-service
spec:
  selector:
    app: my-rnn-model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # The port exposed by the container
  type: LoadBalancer
